version: "3"
volumes:
  uploads:

services:
  redis:
    image: redis:6.0-alpine
  flask:
    build:
      context: ./webserver/
      dockerfile: ./flask/Dockerfile
    env_file: ./webserver/flask/flask.env
    ports:
      - 5000:5000
    depends_on:
      - celery
    volumes:
      - uploads:/var/www/uploads
  celery:
    build: ./webserver/celery
    env_file: ./webserver/celery/celery.env
    ports:
      - 5555:5555
    depends_on:
      - redis
    volumes:
      - uploads:/uploads
