version: "3"
services:
  flask:
    build:
      context: ./webserver/
      dockerfile: ./flask/Dockerfile
    env_file: ./webserver/flask/flask.env
    ports:
      - 5000:5000
    depends_on:
      - celery
  celery:
    build: ./webserver/celery
    env_file: ./webserver/celery/celery.env
    ports:
      - 5555:5555
