#HARDCODED VALUES TO BE DELETED
sender: se101kajag@gmail.com
success_subject: "KAJAG: Your File is Ready!"
success_message: |
  Hello,

  Your scan has been sucessfully converted into a LaTeX document.
  Please find attatched a pdf file containing your scan.

failure_subject: "KAJAG: File Failed to Convert"
failure_message: |
  Hello,

  We have received an image from you that does not contain any recognizable written features to convert into a LaTeX document. Please try again.
